"""add stock transfer table

Revision ID: 1dcb4699213a
Revises: 60f068f4625a
Create Date: 2026-09-01 14:31:30.804931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1dcb4699213a'
down_revision: Union[str, Sequence[str], None] = '60f068f4625a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stock_transfers', 'source_warehouse_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('stock_transfers', 'dest_warehouse_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('stock_transfers', 'qty')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock_transfers', sa.Column('qty', sa.INTEGER(), autoincrement=False, nullable=False))
    op.alter_column('stock_transfers', 'dest_warehouse_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('stock_transfers', 'source_warehouse_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
