"""add sales order changes

Revision ID: 60f068f4625a
Revises: bfaf79099205
Create Date: 2026-09-01 14:06:56.933342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60f068f4625a'
down_revision: Union[str, Sequence[str], None] = 'bfaf79099205'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sales_orders', 'ordered_qty')
    op.drop_column('sales_orders', 'fulfilled_qty')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales_orders', sa.Column('fulfilled_qty', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('sales_orders', sa.Column('ordered_qty', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
