"""add purchase orders and items tables

Revision ID: d0034940f4d6
Revises: d7479ea3cc8b
Create Date: 2026-08-31 16:29:38.692546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0034940f4d6'
down_revision: Union[str, Sequence[str], None] = 'd7479ea3cc8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('purchase_order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purchase_order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('ordered_qty', sa.Integer(), nullable=False),
    sa.Column('received_qty', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_order_items_id'), 'purchase_order_items', ['id'], unique=False)
    op.add_column('purchase_orders', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.alter_column('purchase_orders', 'vendor_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('purchase_orders', 'warehouse_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('purchase_orders', 'received_qty')
    op.drop_column('purchase_orders', 'ordered_qty')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_orders', sa.Column('ordered_qty', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('purchase_orders', sa.Column('received_qty', sa.INTEGER(), autoincrement=False, nullable=True))
    op.alter_column('purchase_orders', 'warehouse_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('purchase_orders', 'vendor_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('purchase_orders', 'created_at')
    op.drop_index(op.f('ix_purchase_order_items_id'), table_name='purchase_order_items')
    op.drop_table('purchase_order_items')
    # ### end Alembic commands ###
